const actions = {
  ACTIVITY_CALLBACK_REQUEST: 'ACTIVITY_CALLBACK_REQUEST',
  ACTIVITY_CALLBACK_REQUEST_SUCCESS: 'ACTIVITY_CALLBACK_REQUEST_SUCCESS',
  ACTIVITY_CALLBACK_REQUEST_ERROR: 'ACTIVITY_CALLBACK_REQUEST_ERROR',

  getCallbackRequest: (payload) => ({
    type: actions.ACTIVITY_CALLBACK_REQUEST,
    payload,
  }),
};

export default actions;
