const actions = {
  CONTENT_LO_CHECKLIST: 'CONTENT_LO_CHECKLIST',
  CONTENT_LO_CHECKLIST_SUCCESS: 'CONTENT_LO_CHECKLIST_SUCCESS',
  CONTENT_LO_CHECKLIST_ERROR: 'CONTENT_LO_CHECKLIST_ERROR',

  DELETE_CONTENT_LO_CHECKLIST: 'DELETE_CONTENT_LO_CHECKLIST',
  DELETE_CONTENT_LO_CHECKLIST_SUCCESS: 'DELETE_CONTENT_LO_CHECKLIST_SUCCESS',
  DELETE_CONTENT_LO_CHECKLIST_ERROR: 'DELETE_CONTENT_LO_CHECKLIST_ERROR',

  DELETE_CONTENT_LO_CHECKLIST_ITEM: 'DELETE_CONTENT_LO_CHECKLIST_ITEM',
  DELETE_CONTENT_LO_CHECKLIST_ITEM_SUCCESS:
    'DELETE_CONTENT_LO_CHECKLIST_ITEM_SUCCESS',
  DELETE_CONTENT_LO_CHECKLIST_ITEM_ERROR:
    'DELETE_CONTENT_LO_CHECKLIST_ITEM_ERROR',

  DEFAULT_CONTENT_LO_CHECKLIST: 'DEFAULT_CONTENT_LO_CHECKLIST',
  DEFAULT_CONTENT_LO_CHECKLIST_SUCCESS: 'DEFAULT_CONTENT_LO_CHECKLIST_SUCCESS',
  DEFAULT_CONTENT_LO_CHECKLIST_ERROR: 'DEFAULT_CONTENT_LO_CHECKLIST_ERROR',

  SAVE_CONTENT_LO_CHECKLIST: 'SAVE_CONTENT_LO_CHECKLIST',
  SAVE_CONTENT_LO_CHECKLIST_SUCCESS: 'SAVE_CONTENT_LO_CHECKLIST_SUCCESS',
  SAVE_CONTENT_LO_CHECKLIST_ERROR: 'SAVE_CONTENT_LO_CHECKLIST_ERROR',

  EDIT_CONTENT_LO_CHECKLIST: 'EDIT_CONTENT_LO_CHECKLIST',
  EDIT_CONTENT_LO_CHECKLIST_SUCCESS: 'EDIT_CONTENT_LO_CHECKLIST_SUCCESS',
  EDIT_CONTENT_LO_CHECKLIST_ERROR: 'EDIT_CONTENT_LO_CHECKLIST_ERROR',

  REARRANGE_LO_CHCKLIST: 'REARRANGE_LO_CHCKLIST',
  REARRANGE_LO_CHCKLIST_SUCCESS: 'REARRANGE_LO_CHCKLIST_SUCCESS',
  REARRANGE_LO_CHCKLIST_ERROR: 'REARRANGE_LO_CHCKLIST_ERROR',

  REARRANGE_LO_CHCKLIST_ITEM: 'REARRANGE_LO_CHCKLIST_ITEM',

  getCheckList: (page) => {
    return {
      type: actions.CONTENT_LO_CHECKLIST,
      payload: page,
    };
  },
  rearrangeChecklist: (payload) => ({
    type: actions.REARRANGE_LO_CHCKLIST,
    payload,
  }),

  rearrangeChecklistItem: (payload) => ({
    type: actions.REARRANGE_LO_CHCKLIST_ITEM,
    payload,
  }),

  editCheckList: (payload) => ({
    type: actions.EDIT_CONTENT_LO_CHECKLIST,
    payload,
  }),

  saveNewCheckList: (payload) => ({
    type: actions.SAVE_CONTENT_LO_CHECKLIST,
    payload,
  }),

  defaultCheckList: () => ({
    type: actions.DEFAULT_CONTENT_LO_CHECKLIST,
  }),
  setIsDefaultDataEmpty: (payload) => ({
    type: actions.DEFAULT_CONTENT_LO_CHECKLIST_ERROR,
    payload,
  }),
  deleteCheckList: (payload) => ({
    type: actions.DELETE_CONTENT_LO_CHECKLIST,
    payload,
  }),
  deleteCheckListItems: (payload) => ({
    type: actions.DELETE_CONTENT_LO_CHECKLIST_ITEM,
    payload,
  }),
};

export default actions;
