const actions = {
  GET_BRANDED_APP: 'GET_BRANDED_APP',
  GET_BRANDED_APP_SUCCESS: 'GET_BRANDED_APP_SUCCESS',
  GET_BRANDED_APP_ERROR: 'GET_BRANDED_APP_ERROR',

  GET_BRANDED_APP_CLIENTS: 'GET_BRANDED_APP_CLIENTS',
  GET_BRANDED_APP_CLIENTS_SUCCESS: 'GET_BRANDED_APP_CLIENTS_SUCCESS',
  GET_BRANDED_APP_CLIENTS_ERROR: 'GET_BRANDED_APP_CLIENTS_ERROR',

  GET_BRANDED_APP_EMPLOYEES: 'GET_BRANDED_APP_EMPLOYEES',
  GET_BRANDED_APP_EMPLOYEES_SUCCESS: 'GET_BRANDED_APP_EMPLOYEES_SUCCESS',
  GET_BRANDED_APP_EMPLOYEES_ERROR: 'GET_BRANDED_APP_EMPLOYEES_ERROR',

  GET_BRANDED_APP_INFO: 'GET_BRANDED_APP_INFO',
  GET_BRANDED_APP_INFO_SUCCESS: 'GET_BRANDED_APP_INFO_SUCCESS',
  GET_BRANDED_APP_INFO_ERROR: 'GET_BRANDED_APP_INFO_ERROR',

  GET_BRANDED_APP_BY_ID: 'GET_BRANDED_APP_BY_ID',
  GET_BRANDED_APP_BY_ID_SUCCESS: 'GET_BRANDED_APP_BY_ID_SUCCESS',
  GET_BRANDED_APP_BY_ID_ERROR: 'GET_BRANDED_APP_BY_ID_ERROR',

  ACCEPT_POST_BRANDED_APP: 'ACCEPT_POST_BRANDED_APP',
  ACCEPT_POST_BRANDED_APP_SUCCESS: 'ACCEPT_POST_BRANDED_APP_SUCCESS',
  ACCEPT_POST_BRANDED_APP_ERROR: 'ACCEPT_POST_BRANDED_APP_ERROR',

  REJECT_POST_BRANDED_APP: 'REJECT_POST_BRANDED_APP',
  REJECT_POST_BRANDED_APP_SUCCESS: 'REJECT_POST_BRANDED_APP_SUCCESS',
  REJECT_POST_BRANDED_APP_ERROR: 'REJECT_POST_BRANDED_APP_ERROR',

  POST_BRANDED_APP_STATUS: 'POST_BRANDED_APP_STATUS',
  POST_BRANDED_APP_STATUS_SUCCESS: 'POST_BRANDED_APP_STATUS_SUCCESS',
  POST_BRANDED_APP_STATUS_ERROR: 'POST_BRANDED_APP_STATUS_ERROR',

  POST_BRANDED_APP_INFO: 'POST_BRANDED_APP_INFO',
  POST_BRANDED_APP_INFO_SUCCESS: 'POST_BRANDED_APP_INFO_SUCCESS',
  POST_BRANDED_APP_INFO_ERROR: 'POST_BRANDED_APP_INFO_ERROR',

  BRANDED_APP_PAGE_DETAILES: 'BRANDED_APP_PAGE_DETAILES',

  getBrandedApp: (payload) => ({
    type: actions.GET_BRANDED_APP,
    payload,
  }),

  getBrandedAppClients: (payload) => ({
    type: actions.GET_BRANDED_APP_CLIENTS,
    payload,
  }),
  getBrandedAppEmployees: (payload, id) => ({
    type: actions.GET_BRANDED_APP_EMPLOYEES,
    payload,
    id,
  }),

  saveBrandedappPageDetailes: (payload) => ({
    type: actions.BRANDED_APP_PAGE_DETAILES,
    payload,
  }),

  getBrandedAppInfo: () => ({
    type: actions.GET_BRANDED_APP_INFO,
  }),

  getBrandedAppByID: (payload) => ({
    type: actions.GET_BRANDED_APP_BY_ID,
    payload,
  }),

  acceptBrrandedApp: (payload) => ({
    type: actions.ACCEPT_POST_BRANDED_APP,
    payload,
  }),
  rejectBrandedApp: (payload) => ({
    type: actions.REJECT_POST_BRANDED_APP,
    payload,
  }),
  setBrandedAppInfo: (payload) => ({
    type: actions.POST_BRANDED_APP_INFO,
    payload,
  }),

  setBrandedAppStatus: (payload) => ({
    type: actions.POST_BRANDED_APP_STATUS,
    payload,
  }),
};

export default actions;
