const actions = {
  APP_DEFAULT_FEES: 'APP_DEFAULT_FEES',
  APP_DEFAULT_FEES_SUCCESS: 'APP_DEFAULT_FEES_SUCCESS',
  APP_DEFAULT_FEES_ERROR: 'APP_DEFAULT_FEES_ERROR',

  EDIT_APP_DEFAULT_FEES: 'EDIT_APP_DEFAULT_FEES',
  EDIT_APP_DEFAULT_FEES_SUCCESS: 'EDIT_APP_DEFAULT_FEES_SUCCESS',
  EDIT_APP_DEFAULT_FEES_ERROR: 'EDIT_APP_DEFAULT_FEES_ERROR',

  SAVE_APP_DEFAULT_FEES: 'SAVE_APP_DEFAULT_FEES',
  SAVE_APP_DEFAULT_FEES_SUCCESS: 'SAVE_APP_DEFAULT_FEES_SUCCESS',
  SAVE_APP_DEFAULT_FEES_ERROR: 'SAVE_APP_DEFAULT_FEES_ERROR',

  DELETE_APP_DEFAULT_FEES: 'DELETE_APP_DEFAULT_FEES',
  DELETE_APP_DEFAULT_FEES_SUCCESS: 'DELETE_APP_DEFAULT_FEES_SUCCESS',
  DELETE_APP_DEFAULT_FEES_ERROR: 'DELETE_APP_DEFAULT_FEES_ERROR',

  getFees: () => {
    return {
      type: actions.APP_DEFAULT_FEES,
    };
  },

  editFees: (payload) => ({
    type: actions.EDIT_APP_DEFAULT_FEES,
    payload,
  }),

  saveNewFees: (payload) => ({
    type: actions.SAVE_APP_DEFAULT_FEES,
    payload,
  }),
  deleteAppDefFees: (payload) => ({
    type: actions.DELETE_APP_DEFAULT_FEES,
    payload,
  }),
};

export default actions;
