const actions = {
  LOAN_SETTINGS_FEES: 'LOAN_SETTINGS_FEES',
  LOAN_SETTINGS_FEES_SUCCESS: 'LOAN_SETTINGS_FEES_SUCCESS',
  LOAN_SETTINGS_FEES_ERROR: 'LOAN_SETTINGS_FEES_ERROR',

  EDIT_LOAN_SETTINGS_FEES: 'EDIT_LOAN_SETTINGS_FEES',
  EDIT_LOAN_SETTINGS_FEES_SUCCESS: 'EDIT_LOAN_SETTINGS_FEES_SUCCESS',
  EDIT_LOAN_SETTINGS_FEES_ERROR: 'EDIT_LOAN_SETTINGS_FEES_ERROR',

  SAVE_LOAN_SETTINGS_FEES: 'SAVE_LOAN_SETTINGS_FEES',
  SAVE_LOAN_SETTINGS_FEES_SUCCESS: 'SAVE_LOAN_SETTINGS_FEES_SUCCESS',
  SAVE_LOAN_SETTINGS_FEES_ERROR: 'SAVE_LOAN_SETTINGS_FEES_ERROR',

  DELETE_LOAN_SETTINGS_FEES: 'DELETE_LOAN_SETTINGS_FEES',
  DELETE_LOAN_SETTINGS_FEES_SUCCESS: 'DELETE_LOAN_SETTINGS_FEES_SUCCESS',
  DELETE_LOAN_SETTINGS_FEES_ERROR: 'DELETE_LOAN_SETTINGS_FEES_ERROR',

  getFees: () => {
    return {
      type: actions.LOAN_SETTINGS_FEES,
    };
  },

  editFees: (payload) => ({
    type: actions.EDIT_LOAN_SETTINGS_FEES,
    payload,
  }),

  saveNewFees: (payload) => ({
    type: actions.SAVE_LOAN_SETTINGS_FEES,
    payload,
  }),
  deleteAppDefFees: (payload) => ({
    type: actions.DELETE_LOAN_SETTINGS_FEES,
    payload,
  }),
};

export default actions;
