const actions = {
  CALCULATOR_USDA: 'CALCULATOR_USDA',
  CALCULATOR_USDA_SUCCESS: 'CALCULATOR_USDA_SUCCESS',
  CALCULATOR_USDA_ERROR: 'CALCULATOR_USDA_ERROR',

  SAVE_CALCULATOR_USDA: 'SAVE_CALCULATOR_USDA',
  SAVE_CALCULATOR_USDA_SUCCESS: 'SAVE_CALCULATOR_USDA_SUCCESS',
  SAVE_CALCULATOR_USDA_ERROR: 'SAVE_CALCULATOR_USDA_ERROR',

  DELETE_CALCULATOR_USDA_LOAN_FECTOR: 'DELETE_CALCULATOR_USDA_LOAN_FACTOR',
  DELETE_CALCULATOR_USDA_LOAN_FECTOR_SUCCESS:
    'DELETE_CALCULATOR_USDA_LOAN_FECTOR_SUCCESS',
  DELETE_CALCULATOR_USDA_LOAN_FECTOR_ERROR:
    'DELETE_CALCULATOR_USDA_LOAN_FECTOR_ERROR',

  getUSDA: () => {
    return {
      type: actions.CALCULATOR_USDA,
    };
  },

  saveUSDA: (payload) => ({
    type: actions.SAVE_CALCULATOR_USDA,
    payload,
  }),
  deleteUSDALoanFector: (payload) => ({
    type: actions.DELETE_CALCULATOR_USDA_LOAN_FECTOR,
    payload,
  }),
};

export default actions;
