const actions = {
  APP_DEFAULT_LEARNING_CENTER: 'APP_DEFAULT_LEARNING_CENTER',
  APP_DEFAULT_LEARNING_CENTER_SUCCESS: 'APP_DEFAULT_LEARNING_CENTER_SUCCESS',
  APP_DEFAULT_LEARNING_CENTER_ERROR: 'APP_DEFAULT_LEARNING_CENTER_ERROR',

  SAVE_APP_DEFAULT_LEARNING_CENTER: 'SAVE_APP_DEFAULT_LEARNING_CENTER',
  SAVE_APP_DEFAULT_LEARNING_CENTER_SUCCESS:
    'SAVE_APP_DEFAULT_LEARNING_CENTER_SUCCESS',
  SAVE_APP_DEFAULT_LEARNING_CENTER_ERROR:
    'SAVE_APP_DEFAULT_LEARNING_CENTER_ERROR',

  DEFAULT_APP_DEFAULT_LEARNING_CENTER: 'DEFAULT_APP_DEFAULT_LEARNING_CENTER',
  DEFAULT_APP_DEFAULT_LEARNING_CENTER_SUCCESS:
    'DEFAULT_APP_DEFAULT_LEARNING_CENTER_SUCCESS',
  DEFAULT_APP_DEFAULT_LEARNING_CENTER_ERROR:
    'DEFAULT_APP_DEFAULT_LEARNING_CENTER_ERROR',

  EDIT_APP_DEFAULT_LEARNING_CENTER: 'EDIT_APP_DEFAULT_LEARNING_CENTER',
  EDIT_APP_DEFAULT_LEARNING_CENTER_SUCCESS:
    'EDIT_APP_DEFAULT_LEARNING_CENTER_SUCCESS',
  EDIT_APP_DEFAULT_LEARNING_CENTER_ERROR:
    'EDIT_APP_DEFAULT_LEARNING_CENTER_ERROR',

  DELETE_APP_DEFAULT_LEARNING_CENTER: 'DELETE_APP_DEFAULT_LEARNING_CENTER',
  DELETE_APP_DEFAULT_LEARNING_CENTER_SUCCESS:
    'DELETE_APP_DEFAULT_LEARNING_CENTER_SUCCESS',
  DELETE_APP_DEFAULT_LEARNING_CENTER_ERROR:
    'DELETE_APP_DEFAULT_LEARNING_CENTER_ERROR',

  learningCenterList: (payload) => {
    return {
      type: actions.APP_DEFAULT_LEARNING_CENTER,
      payload,
    };
  },
  defaultLearningCenterList: () => ({
    type: actions.DEFAULT_APP_DEFAULT_LEARNING_CENTER,
  }),
  setIsDefaultDataEmpty: (payload) => ({
    type: actions.DEFAULT_APP_DEFAULT_LEARNING_CENTER_ERROR,
    payload,
  }),
  editLearningCenter: (payload) => ({
    type: actions.EDIT_APP_DEFAULT_LEARNING_CENTER,
    payload,
  }),
  deleteLearningCenter: (payload) => ({
    type: actions.DELETE_APP_DEFAULT_LEARNING_CENTER,
    payload,
  }),

  saveLearningCenter: (payload) => ({
    type: actions.SAVE_APP_DEFAULT_LEARNING_CENTER,
    payload,
  }),
};

export default actions;
