const actions = {
  APP_DEFAULT_GLOSSARY: 'APP_DEFAULT_GLOSSARY',
  APP_DEFAULT_GLOSSARY_SUCCESS: 'APP_DEFAULT_GLOSSARY_SUCCESS',
  APP_DEFAULT_GLOSSARY_ERROR: 'APP_DEFAULT_GLOSSARY_ERROR',

  EDIT_APP_DEFAULT_GLOSSARY: 'EDIT_APP_DEFAULT_GLOSSARY',
  EDIT_APP_DEFAULT_GLOSSARY_SUCCESS: 'EDIT_APP_DEFAULT_GLOSSARY_SUCCESS',
  EDIT_APP_DEFAULT_GLOSSARY_ERROR: 'EDIT_APP_DEFAULT_GLOSSARY_ERROR',

  DELETE_APP_DEFAULT_GLOSSARY: 'DELETE_APP_DEFAULT_GLOSSARY',
  DELETE_APP_DEFAULT_GLOSSARY_SUCCESS: 'DELETE_APP_DEFAULT_GLOSSARY_SUCCESS',
  DELETE_APP_DEFAULT_GLOSSARY_ERROR: 'DELETE_APP_DEFAULT_GLOSSARY_ERROR',

  ADD_APP_DEFAULT_GLOSSARY: 'ADD_APP_DEFAULT_GLOSSARY',
  ADD_APP_DEFAULT_GLOSSARY_SUCCESS: 'ADD_APP_DEFAULT_GLOSSARY_SUCCESS',
  ADD_APP_DEFAULT_GLOSSARY_ERROR: 'ADD_APP_DEFAULT_GLOSSARY_ERROR',

  getGlossary: (payload) => {
    return {
      type: actions.APP_DEFAULT_GLOSSARY,
      payload,
    };
  },

  addGlosarry: (payload) => ({
    type: actions.ADD_APP_DEFAULT_GLOSSARY,
    payload,
  }),

  editGlosarry: (payload) => ({
    type: actions.EDIT_APP_DEFAULT_GLOSSARY,
    payload,
  }),
  deleteGlosarry: (payload) => ({
    type: actions.DELETE_APP_DEFAULT_GLOSSARY,
    payload,
  }),
};

export default actions;
