const actions = {
  APP_DEF_LOAN_PROGRAM: 'APP_DEF_LOAN_PROGRAM',
  APP_DEF_LOAN_PROGRAM_SUCCESS: 'APP_DEF_LOAN_PROGRAM_SUCCESS',
  APP_DEF_LOAN_PROGRAM_ERROR: 'APP_DEF_LOAN_PROGRAM_ERROR',

  SAVE_APP_DEF_LOAN_PROGRAM: 'SAVE_APP_DEF_LOAN_PROGRAM',
  SAVE_APP_DEF_LOAN_PROGRAM_SUCCESS: 'SAVE_APP_DEF_LOAN_PROGRAM_SUCCESS',
  SAVE_APP_DEF_LOAN_PROGRAM_ERROR: 'SAVE_APP_DEF_LOAN_PROGRAM_ERROR',

  DEFAULT_APP_DEF_LOAN_PROGRAM: 'DEFAULT_APP_DEF_LOAN_PROGRAM',
  DEFAULT_APP_DEF_LOAN_PROGRAM_SUCCESS: 'DEFAULT_APP_DEF_LOAN_PROGRAM_SUCCESS',
  DEFAULT_APP_DEF_LOAN_PROGRAM_ERROR: 'DEFAULT_APP_DEF_LOAN_PROGRAM_ERROR',

  EDIT_APP_DEF_LOAN_PROGRAM: 'EDIT_APP_DEF_LOAN_PROGRAM',
  EDIT_APP_DEF_LOAN_PROGRAM_SUCCESS: 'EDIT_APP_DEF_LOAN_PROGRAM_SUCCESS',
  EDIT_APP_DEF_LOAN_PROGRAM_ERROR: 'EDIT_APP_DEF_LOAN_PROGRAM_ERROR',

  DELETE_APP_DEF_LOAN_PROGRAM: 'DELETE_APP_DEF_LOAN_PROGRAM',
  DELETE_APP_DEF_LOAN_PROGRAM_SUCCESS: 'DELETE_APP_DEF_LOAN_PROGRAM_SUCCESS',
  DELETE_APP_DEF_LOAN_PROGRAM_ERROR: 'DELETE_APP_DEF_LOAN_PROGRAM_ERROR',

  loanProgramList: (payload) => {
    return {
      type: actions.APP_DEF_LOAN_PROGRAM,
      payload,
    };
  },
  defaultLoanProgramList: () => ({
    type: actions.DEFAULT_APP_DEF_LOAN_PROGRAM,
  }),
  setIsDefaultDataEmpty: (payload) => ({
    type: actions.DEFAULT_APP_DEF_LOAN_PROGRAM_ERROR,
    payload,
  }),
  editLoanProgram: (payload) => ({
    type: actions.EDIT_APP_DEF_LOAN_PROGRAM,
    payload,
  }),
  deleteLoanProgram: (payload) => ({
    type: actions.DELETE_APP_DEF_LOAN_PROGRAM,
    payload,
  }),

  saveLoanProgram: (type) => ({
    type: actions.SAVE_APP_DEF_LOAN_PROGRAM,
    payload: type,
  }),
};

export default actions;
