const actions = {
  JUMBO_CALCULATOR: 'JUMBO_CALCULATOR',
  JUMBO_CALCULATOR_SUCCESS: 'JUMBO_CALCULATOR_SUCCESS',
  JUMBO_CALCULATOR_ERROR: 'JUMBO_CALCULATOR_ERROR',

  SAVE_JUMBO_CALCULATOR: 'SAVE_JUMBO_CALCULATOR',
  SAVE_JUMBO_CALCULATOR_SUCCESS: 'SAVE_JUMBO_CALCULATOR_SUCCESS',
  SAVE_JUMBO_CALCULATOR_ERROR: 'SAVE_JUMBO_CALCULATOR_ERROR',

  DELETE_JUMBO_CALCULATOR_LOAN_FECTOR: 'DELETE_JUMBO_CALCULATOR_LOAN_FACTOR',
  DELETE_JUMBO_CALCULATOR_LOAN_FECTOR_SUCCESS:
    'DELETE_JUMBO_CALCULATOR_LOAN_FECTOR_SUCCESS',
  DELETE_JUMBO_CALCULATOR_LOAN_FECTOR_ERROR:
    'DELETE_JUMBO_CALCULATOR_LOAN_FECTOR_ERROR',

  getJumbo: () => {
    return {
      type: actions.JUMBO_CALCULATOR,
    };
  },

  saveJumbo: (payload) => ({
    type: actions.SAVE_JUMBO_CALCULATOR,
    payload,
  }),
  deleteJumboLoanFector: (payload) => ({
    type: actions.DELETE_JUMBO_CALCULATOR_LOAN_FECTOR,
    payload,
  }),
};

export default actions;
