const actions = {
  ADMIN_SUBSCRIPTION_PLAN: 'ADMIN_SUBSCRIPTION_PLAN',
  ADMIN_SUBSCRIPTION_PLAN_SUCCESS: 'ADMIN_SUBSCRIPTION_PLAN_SUCCESS',
  ADMIN_SUBSCRIPTION_PLAN_ERROR: 'ADMIN_SUBSCRIPTION_PLAN_ERROR',

  SAVE_ADMIN_SUBSCRIPTION_PLAN: 'SAVE_ADMIN_SUBSCRIPTION_PLAN',
  SAVE_ADMIN_SUBSCRIPTION_PLAN_SUCCESS: 'SAVE_ADMIN_SUBSCRIPTION_PLAN_SUCCESS',
  SAVE_ADMIN_SUBSCRIPTION_PLAN_ERROR: 'SAVE_ADMIN_SUBSCRIPTION_PLAN_ERROR',

  VIEW_ADMIN_SUBSCRIPTION_PLAN: 'VIEW_ADMIN_SUBSCRIPTION_PLAN',
  VIEW_ADMIN_SUBSCRIPTION_PLAN_SUCCESS: 'VIEW_ADMIN_SUBSCRIPTION_PLAN_SUCCESS',
  VIEW_ADMIN_SUBSCRIPTION_PLAN_ERROR: 'VIEW_ADMIN_SUBSCRIPTION_PLAN_ERROR',

  EDIT_ADMIN_SUBSCRIPTION_PLAN: 'EDIT_ADMIN_SUBSCRIPTION_PLAN',
  EDIT_ADMIN_SUBSCRIPTION_PLAN_SUCCESS: 'EDIT_ADMIN_SUBSCRIPTION_PLAN_SUCCESS',
  EDIT_ADMIN_SUBSCRIPTION_PLAN_ERROR: 'EDIT_ADMIN_SUBSCRIPTION_PLAN_ERROR',

  DELETE_ADMIN_SUBSCRIPTION_PLAN: 'DELETE_ADMIN_SUBSCRIPTION_PLAN',
  DELETE_ADMIN_SUBSCRIPTION_PLAN_SUCCESS:
    'DELETE_ADMIN_SUBSCRIPTION_PLAN_SUCCESS',
  DELETE_ADMIN_SUBSCRIPTION_PLAN_ERROR: 'DELETE_ADMIN_SUBSCRIPTION_PLAN_ERROR',

  subscriptionPlanList: () => {
    return {
      type: actions.ADMIN_SUBSCRIPTION_PLAN,
    };
  },
  viewSubscriptionPlan: (payload) => ({
    type: actions.VIEW_ADMIN_SUBSCRIPTION_PLAN,
    payload,
  }),

  editSubscriptionPlan: (payload) => ({
    type: actions.EDIT_ADMIN_SUBSCRIPTION_PLAN,
    payload,
  }),
  deleteSubscriptionPlan: (payload) => ({
    type: actions.DELETE_ADMIN_SUBSCRIPTION_PLAN,
    payload,
  }),

  saveSubscriptionPlan: (payload) => ({
    type: actions.SAVE_ADMIN_SUBSCRIPTION_PLAN,
    payload,
  }),
};

export default actions;
