const actions = {
  GET_APPROVED_BRANDED_APP: 'GET_APPROVED_BRANDED_APP',
  GET_APPROVED_BRANDED_APP_SUCCESS: 'GET_APPROVED_BRANDED_APP_SUCCESS',
  GET_APPROVED_BRANDED_APP_ERROR: 'GET_APPROVED_BRANDED_APP_ERROR',

  GET_APPROVED_BRANDED_APP_INFO: 'GET_APPROVED_BRANDED_APP_INFO',
  GET_APPROVED_BRANDED_APP_INFO_SUCCESS:
    'GET_APPROVED_BRANDED_APP_INFO_SUCCESS',
  GET_APPROVED_BRANDED_APP_INFO_ERROR: 'GET_APPROVED_BRANDED_APP_INFO_ERROR',

  GET_PLAYSTORE_STATUS: 'GET_PLAYSTORE_STATUS',
  GET_PLAYSTORE_STATUS_SUCCESS: 'GET_PLAYSTORE_STATUS_SUCCESS',

  GET_BRANDED_APP_USER: 'GET_BRANDED_APP_USER',
  GET_BRANDED_APP_USER_SUCCESS: 'GET_BRANDED_APP_USER_SUCCESS',
  GET_BRANDED_APP_USER_ERROR: 'GET_BRANDED_APP_USER_ERROR',

  GET_BRANDED_APP_BILLING_HISTORY: 'GET_BRANDED_APP_BILLING_HISTORY',
  GET_BRANDED_APP_BILLING_HISTORY_SUCCESS:
    'GET_BRANDED_APP_BILLING_HISTORY_SUCCESS',
  GET_BRANDED_APP_BILLING_HISTORY_ERROR:
    'GET_BRANDED_APP_BILLING_HISTORY_ERROR',

  APPLY_BRANDED_APP: 'APPLY_BRANDED_APP',
  APPLY_BRANDED_APP_SUCCESS: 'APPLY_BRANDED_APP_SUCCESS',
  APPLY_BRANDED_APP_ERROR: 'APPLY_BRANDED_APP_ERROR',

  CANCEL_SUBSCRIPTIO_BRANDED_APP: 'CANCEL_SUBSCRIPTIO_BRANDED_APP',
  CANCEL_SUBSCRIPTIO_BRANDED_APP_SUCCESS:
    'CANCEL_SUBSCRIPTIO_BRANDED_APP_SUCCESS',
  CANCEL_SUBSCRIPTIO_BRANDED_APP_ERROR: 'CANCEL_SUBSCRIPTIO_BRANDED_APP_ERROR',

  GET_BILLING_DETAIL: 'GET_BILLING_DETAIL',
  GET_BILLING_DETAIL_SUCCESS: 'GET_BILLING_DETAIL_SUCCESS',
  GET_BILLING_DETAIL_ERROR: 'GET_BILLING_DETAIL_ERROR',

  GET_SUBSCRIPTIO_BRANDED_APP: 'GET_SUBSCRIPTIO_BRANDED_APP',
  GET_SUBSCRIPTIO_BRANDED_APP_SUCCESS: 'GET_SUBSCRIPTIO_BRANDED_APP_SUCCESS',
  GET_SUBSCRIPTIO_BRANDED_APP_ERROR: 'GET_SUBSCRIPTIO_BRANDED_APP_ERROR',

  DELETE_LO_BRANDED_APP: 'DELETE_LO_BRANDED_APP',
  DELETE_LO_BRANDED_APP_SUCCESS: 'DELETE_LO_BRANDED_APP_SUCCESS',
  DELETE_LO_BRANDED_APP_ERROR: 'DELETE_LO_BRANDED_APP_ERROR',

  ADD_LOAN_OFFICER_BRANDED_APP: 'ADD_LOAN_OFFICER_BRANDED_APP',
  ADD_LOAN_OFFICER_BRANDED_APP_SUCCESS: 'ADD_LOAN_OFFICER_BRANDED_APP_SUCCESS',
  ADD_LOAN_OFFICER_BRANDED_APP_ERROR: 'ADD_LOAN_OFFICER_BRANDED_APP_ERROR',

  SUBSCRIBE_BRANDED_APP: 'SUBSCRIBE_BRANDED_APP',
  SUBSCRIBE_BRANDED_APP_SUCCESS: 'SUBSCRIBE_BRANDED_APP_SUCCESS',
  SUBSCRIBE_BRANDED_APP_ERROR: 'SUBSCRIBE_BRANDED_APP_ERROR',

  getApprovedBrandedApp: (payload) => ({
    type: actions.GET_APPROVED_BRANDED_APP,
    payload,
  }),
  getBrandedAppInfo: () => ({
    type: actions.GET_APPROVED_BRANDED_APP_INFO,
  }),
  getPlayStoreStatus: () => ({
    type: actions.GET_PLAYSTORE_STATUS,
  }),
  getBrandedAppUser: () => ({
    type: actions.GET_BRANDED_APP_USER,
  }),

  getBillingHistoryBApp: () => {
    return {
      type: actions.GET_BRANDED_APP_BILLING_HISTORY,
    };
  },
  addLoanOfficerBrrandedApp: (payload) => ({
    type: actions.ADD_LOAN_OFFICER_BRANDED_APP,
    payload,
  }),
  postSubscibeBrandedApp: (payload) => ({
    type: actions.SUBSCRIBE_BRANDED_APP,
    payload,
  }),
  deleteLoanOficerBrandedApp: (payload) => ({
    type: actions.DELETE_LO_BRANDED_APP,
    payload,
  }),

  applyBrandedApp: (payload) => ({
    type: actions.APPLY_BRANDED_APP,
    payload,
  }),
  getSubscriptionBrandedApp: (payload) => ({
    type: actions.GET_SUBSCRIPTIO_BRANDED_APP,
    payload,
  }),
  cancelSubscriptionBrandedApp: (payload) => ({
    type: actions.CANCEL_SUBSCRIPTIO_BRANDED_APP,
    payload,
  }),
  getBillingDetail: () => ({
    type: actions.GET_BILLING_DETAIL,
  }),
};

export default actions;
