const actions = {
  MARKETING_AUTO_RESPONDER: 'MARKETING_AUTO_RESPONDER',
  MARKETING_AUTO_RESPONDER_SUCCESS: 'MARKETING_AUTO_RESPONDER_SUCCESS',
  MARKETING_AUTO_RESPONDER_ERROR: 'MARKETING_AUTO_RESPONDER_ERROR',

  UPDATE_MARKETING_AUTO_RESPONDER: 'UPDATE_MARKETING_AUTO_RESPONDER',
  UPDATE_MARKETING_AUTO_RESPONDER_SUCCESS:
    'UPDATE_MARKETING_AUTO_RESPONDER_SUCCESS',
  UPDATE_MARKETING_AUTO_RESPONDER_ERROR:
    'UPDATE_MARKETING_AUTO_RESPONDER_ERROR',

  DEFAULT_LO_AUTO_RESPONDER: 'DEFAULT_LO_AUTO_RESPONDER',
  DEFAULT_LO_AUTO_RESPONDER_SUCCESS: 'DEFAULT_LO_AUTO_RESPONDER_SUCCESS',
  DEFAULT_LO_AUTO_RESPONDER_ERROR: 'DEFAULT_LO_AUTO_RESPONDER_ERROR',

  getAutoresponder: () => {
    return {
      type: actions.MARKETING_AUTO_RESPONDER,
    };
  },

  updateAutoResponder: (payload) => ({
    type: actions.UPDATE_MARKETING_AUTO_RESPONDER,
    payload,
  }),
  defaultAutoResponder: () => ({
    type: actions.DEFAULT_LO_AUTO_RESPONDER,
  }),
};

export default actions;
