const actions = {
  CALCULATOR_USDA_ADMIN: 'CALCULATOR_USDA_ADMIN',
  CALCULATOR_USDA_ADMIN_SUCCESS: 'CALCULATOR_USDA_ADMIN_SUCCESS',
  CALCULATOR_USDA_ADMIN_ERROR: 'CALCULATOR_USDA_ADMIN_ERROR',

  SAVE_CALCULATOR_USDA_ADMIN: 'SAVE_CALCULATOR_USDA_ADMIN',
  SAVE_CALCULATOR_USDA_ADMIN_SUCCESS: 'SAVE_CALCULATOR_USDA_ADMIN_SUCCESS',
  SAVE_CALCULATOR_USDA_ADMIN_ERROR: 'SAVE_CALCULATOR_USDA_ADMIN_ERROR',

  DELETE_CALCULATOR_USDA_ADMIN_LOAN_FECTOR:
    'DELETE_CALCULATOR_USDA_ADMIN_LOAN_FACTOR',
  DELETE_CALCULATOR_USDA_ADMIN_LOAN_FECTOR_SUCCESS:
    'DELETE_CALCULATOR_USDA_ADMIN_LOAN_FECTOR_SUCCESS',
  DELETE_CALCULATOR_USDA_ADMIN_LOAN_FECTOR_ERROR:
    'DELETE_CALCULATOR_USDA_ADMIN_LOAN_FECTOR_ERROR',

  getUSDA: () => {
    return {
      type: actions.CALCULATOR_USDA_ADMIN,
    };
  },

  saveUSDA: (payload) => ({
    type: actions.SAVE_CALCULATOR_USDA_ADMIN,
    payload,
  }),
  deleteUSDALoanFector: (payload) => ({
    type: actions.DELETE_CALCULATOR_USDA_ADMIN_LOAN_FECTOR,
    payload,
  }),
};

export default actions;
