const actions = {
  CALCULATOR_VA_ADMIN: 'CALCULATOR_VA_ADMIN',
  CALCULATOR_VA_ADMIN_SUCCESS: 'CALCULATOR_VA_ADMIN_SUCCESS',
  CALCULATOR_VA_ADMIN_ERROR: 'CALCULATOR_VA_ADMIN_ERROR',

  SAVE_CALCULATOR_VA_ADMIN: 'SAVE_CALCULATOR_VA_ADMIN',
  SAVE_CALCULATOR_VA_ADMIN_SUCCESS: 'SAVE_CALCULATOR_VA_ADMIN_SUCCESS',
  SAVE_CALCULATOR_VA_ADMIN_ERROR: 'SAVE_CALCULATOR_VA_ADMIN_ERROR',

  getVA: () => {
    return {
      type: actions.CALCULATOR_VA_ADMIN,
    };
  },

  saveVA: (payload) => ({
    type: actions.SAVE_CALCULATOR_VA_ADMIN,
    payload,
  }),
};

export default actions;
