const actions = {
  CONVENTIONAL_CALCULATOR: 'CONVENTIONAL_CALCULATOR',
  CONVENTIONAL_CALCULATOR_SUCCESS: 'CONVENTIONAL_CALCULATOR_SUCCESS',
  CONVENTIONAL_CALCULATOR_ERROR: 'CONVENTIONAL_CALCULATOR_ERROR',

  SAVE_CONVENTIONAL_CALCULATOR: 'EDIT_CONVENTIONAL_CALCULATOR',
  SAVE_CONVENTIONAL_CALCULATOR_SUCCESS: 'EDIT_CONVENTIONAL_CALCULATOR_SUCCESS',
  SAVE_CONVENTIONAL_CALCULATOR_ERROR: 'EDIT_CONVENTIONAL_CALCULATOR_ERROR',

  DELETE_CONVENTIONAL_CALCULATOR_LOAN_FECTOR:
    'DELETE_CONVENTIONAL_CALCULATOR_LOAN_FACTOR',
  DELETE_CONVENTIONAL_CALCULATOR_LOAN_FECTOR_SUCCESS:
    'DELETE_CONVENTIONAL_CALCULATOR_LOAN_FECTOR_SUCCESS',
  DELETE_CONVENTIONAL_CALCULATOR_LOAN_FECTOR_ERROR:
    'DELETE_CONVENTIONAL_CALCULATOR_LOAN_FECTOR_ERROR',

  getConventional: () => {
    return {
      type: actions.CONVENTIONAL_CALCULATOR,
    };
  },

  saveConventional: (payload) => ({
    type: actions.SAVE_CONVENTIONAL_CALCULATOR,
    payload,
  }),
  deleteConventionalLoanFector: (payload) => ({
    type: actions.DELETE_CONVENTIONAL_CALCULATOR_LOAN_FECTOR,
    payload,
  }),
};

export default actions;
