const actions = {
  GET_ADMIN_SUPPORT_GUIDE: 'GET_ADMIN_SUPPORT_GUIDE',
  GET_ADMIN_SUPPORT_GUIDE_SUCCESS: 'GET_ADMIN_SUPPORT_GUIDE_SUCCESS',
  GET_ADMIN_SUPPORT_GUIDE_ERROR: 'GET_ADMIN_SUPPORT_GUIDE_ERROR',

  GET_ADMIN_SUPPORT_GUIDE_CATEGORY: 'GET_ADMIN_SUPPORT_GUIDE_CATEGORY',
  GET_ADMIN_SUPPORT_GUIDE_CATEGORY_SUCCESS:
    'GET_ADMIN_SUPPORT_GUIDE_CATEGORY_SUCCESS',
  GET_ADMIN_SUPPORT_GUIDE_CATEGORY_ERROR:
    'GET_ADMIN_SUPPORT_GUIDE_CATEGORY_ERROR',

  ADD_ADMIN_SUPPORT_GUIDE_CATEGORY: 'ADD_ADMIN_SUPPORT_GUIDE_CATEGORY',
  ADD_ADMIN_SUPPORT_GUIDE_CATEGORY_SUCCESS:
    'ADD_ADMIN_SUPPORT_GUIDE_CATEGORY_SUCCESS',
  ADD_ADMIN_SUPPORT_GUIDE_CATEGORY_ERROR:
    'ADD_ADMIN_SUPPORT_GUIDE_CATEGORY_ERROR',

  ADD_NEW_ADMIN_SUPPORT_GUIDE: 'ADD_NEW_ADMIN_SUPPORT_GUIDE',
  ADD_NEW_ADMIN_SUPPORT_GUIDE_SUCCESS: 'ADD_NEW_ADMIN_SUPPORT_GUIDE_SUCCESS',
  ADD_NEW_ADMIN_SUPPORT_GUIDE_ERROR: 'ADD_NEW_ADMIN_SUPPORT_GUIDE_ERROR',

  EDIT_ADMIN_SUPPORT_GUIDE: 'EDIT_ADMIN_SUPPORT_GUIDE',
  EDIT_ADMIN_SUPPORT_GUIDE_SUCCESS: 'EDIT_ADMIN_SUPPORT_GUIDE_SUCCESS',
  EDIT_ADMIN_SUPPORT_GUIDE_ERROR: 'EDIT_ADMIN_SUPPORT_GUIDE_ERROR',

  EDIT_ADMIN_SUPPORT_GUIDE_CATEGORY: 'EDIT_ADMIN_SUPPORT_GUIDE_CATEGORY',
  EDIT_ADMIN_SUPPORT_GUIDE_CATEGORY_SUCCESS:
    'EDIT_ADMIN_SUPPORT_GUIDE_CATEGORY_SUCCESS',
  EDIT_ADMIN_SUPPORT_GUIDE_CATEGORY_ERROR:
    'EDIT_ADMIN_SUPPORT_GUIDE_CATEGORY_ERROR',

  DELETE_ADMIN_SUPPORT_GUIDE_CATEGORY: 'DELETE_ADMIN_SUPPORT_GUIDE_CATEGORY',
  DELETE_ADMIN_SUPPORT_GUIDE_CATEGORY_SUCCESS:
    'DELETE_ADMIN_SUPPORT_GUIDE_CATEGORY_SUCCESS',
  DELETE_ADMIN_SUPPORT_GUIDE_CATEGORY_ERROR:
    'DELETE_ADMIN_SUPPORT_GUIDE_CATEGORY_ERROR',

  DELETE_ADMIN_SUPPORT_GUIDE: 'DELETE_ADMIN_SUPPORT_GUIDE',
  DELETE_ADMIN_SUPPORT_GUIDE_SUCCESS: 'DELETE_ADMIN_SUPPORT_GUIDE_SUCCESS',
  DELETE_ADMIN_SUPPORT_GUIDE_ERROR: 'DELETE_ADMIN_SUPPORT_GUIDE_ERROR',

  CHECKED_ADMIN_SUPPORT_GUIDE: 'CHECKED_ADMIN_SUPPORT_GUIDE',
  CHECKED_ADMIN_SUPPORT_GUIDE_SUCCESS: 'CHECKED_ADMIN_SUPPORT_GUIDE_SUCCESS',
  CHECKED_ADMIN_SUPPORT_GUIDE_ERROR: 'CHECKED_ADMIN_SUPPORT_GUIDE_ERROR',

  GET_ADMIN_SUPPORT_FAQS: 'GET_ADMIN_SUPPORT_FAQS',
  GET_ADMIN_SUPPORT_FAQS_SUCCESS: 'GET_ADMIN_SUPPORT_FAQS_SUCCESS',
  GET_ADMIN_SUPPORT_FAQS_ERROR: 'GET_ADMIN_SUPPORT_FAQS_ERROR',

  ADD_ADMIN_SUPPORT_FAQS: 'ADD_ADMIN_SUPPORT_FAQS',

  EDIT_ADMIN_SUPPORT_FAQS: 'EDIT_ADMIN_SUPPORT_FAQS',

  DELETE_ADMIN_SUPPORT_FAQS: 'DELETE_ADMIN_SUPPORT_FAQS',

  REARRANGE_ADMIN_SUPPORT_FAQS: 'REARRANGE_ADMIN_SUPPORT_FAQS',
  REARRANGE_ADMIN_SUPPORT_FAQS_SUCCESS: 'REARRANGE_ADMIN_SUPPORT_FAQS_SUCCESS',
  REARRANGE_ADMIN_SUPPORT_FAQS_ERROR: 'REARRANGE_ADMIN_SUPPORT_FAQS_ERROR',

  GET_ADMIN_SUPPORT_REPS: 'GET_ADMIN_SUPPORT_REPS',
  GET_ADMIN_SUPPORT_REPS_SUCCESS: 'GET_ADMIN_SUPPORT_REPS_SUCCESS',
  GET_ADMIN_SUPPORT_REPS_ERROR: 'GET_ADMIN_SUPPORT_REPS_ERROR',

  SAVE_ADMIN_SUPPORT_REPS: 'SAVE_ADMIN_SUPPORT_REPS',
  SAVE_ADMIN_SUPPORT_REPS_SUCCESS: 'SAVE_ADMIN_SUPPORT_REPS_SUCCESS',
  SAVE_ADMIN_SUPPORT_REPS_ERROR: 'SAVE_ADMIN_SUPPORT_REPS_ERROR',

  DESABLE_ADMIN_SUPPORT_REPS: 'DESABLE_ADMIN_SUPPORT_REPS',
  DESABLE_ADMIN_SUPPORT_REPS_SUCCESS: 'DESABLE_ADMIN_SUPPORT_REPS_SUCCESS',
  DESABLE_ADMIN_SUPPORT_REPS_ERROR: 'DESABLE_ADMIN_SUPPORT_REPS_ERROR',

  getSupportGuide: () => {
    return {
      type: actions.GET_ADMIN_SUPPORT_GUIDE,
    };
  },
  getSupportGuideCategory: () => ({
    type: actions.GET_ADMIN_SUPPORT_GUIDE_CATEGORY,
  }),

  addSupportGuide: (payload) => ({
    type: actions.ADD_NEW_ADMIN_SUPPORT_GUIDE,
    payload,
  }),

  addSupportGuideCategory: (payload) => ({
    type: actions.ADD_ADMIN_SUPPORT_GUIDE_CATEGORY,
    payload,
  }),

  editSupportGuide: (payload) => ({
    type: actions.EDIT_ADMIN_SUPPORT_GUIDE,
    payload,
  }),
  editSupportGuideCategory: (payload) => ({
    type: actions.EDIT_ADMIN_SUPPORT_GUIDE_CATEGORY,
    payload,
  }),

  deleteSupportGuide: (payload) => ({
    type: actions.DELETE_ADMIN_SUPPORT_GUIDE,
    payload,
  }),
  deleteSupportGuideCategory: (payload) => ({
    type: actions.DELETE_ADMIN_SUPPORT_GUIDE_CATEGORY,
    payload,
  }),

  checkedSupportGuide: (payload) => ({
    type: actions.CHECKED_ADMIN_SUPPORT_GUIDE,
    payload,
  }),
  getSupportFaqs: () => {
    return {
      type: actions.GET_ADMIN_SUPPORT_FAQS,
    };
  },
  addSupportFaqs: (payload) => ({
    type: actions.ADD_ADMIN_SUPPORT_FAQS,
    payload,
  }),
  editSupportFaqs: (payload, id) => ({
    type: actions.EDIT_ADMIN_SUPPORT_FAQS,
    payload,
    id,
  }),
  deleteSupportFaqs: (id) => ({
    type: actions.DELETE_ADMIN_SUPPORT_FAQS,
    id,
  }),
  supportFaqsRearrange: (payload) => ({
    type: actions.REARRANGE_ADMIN_SUPPORT_FAQS,
    payload,
  }),
  getSupportReps: () => {
    return {
      type: actions.GET_ADMIN_SUPPORT_REPS,
    };
  },
  saveSupportReps: (payload) => {
    return {
      type: actions.SAVE_ADMIN_SUPPORT_REPS,
      payload,
    };
  },
  desableSupportReps: (payload) => {
    return {
      type: actions.DESABLE_ADMIN_SUPPORT_REPS,
      payload,
    };
  },
};

export default actions;
