const actions = {
  APP_DEFAULT__EMAIL_SIGNATURE: 'APP_DEFAULT__EMAIL_SIGNATURE',
  APP_DEFAULT__EMAIL_SIGNATURE_SUCCESS: 'APP_DEFAULT__EMAIL_SIGNATURE_SUCCESS',
  APP_DEFAULT__EMAIL_SIGNATURE_ERROR: 'APP_DEFAULT__EMAIL_SIGNATURE_ERROR',

  UPLOAD_APP_DEFAULT__EMAIL_SIGNATURE: 'UPLOAD_APP_DEFAULT__EMAIL_SIGNATURE',
  UPLOAD_APP_DEFAULT__EMAIL_SIGNATURE_SUCCESS:
    'UPLOAD_APP_DEFAULT__EMAIL_SIGNATURE_SUCCESS',
  UPLOAD_APP_DEFAULT__EMAIL_SIGNATURE_ERROR:
    'UPLOAD_APP_DEFAULT__EMAIL_SIGNATURE_ERROR',

  APP_DEFAULT_EMAIL_DELETE_SIGNATURE: 'APP_DEFAULT_EMAIL_DELETE_SIGNATURE',
  APP_DEFAULT_EMAIL_DELETE_SIGNATURE_SUCCESS:
    'APP_DEFAULT_EMAIL_DELETE_SIGNATURE_SUCCESS',
  APP_DEFAULT_EMAIL_DELETE_SIGNATURE_ERROR:
    'APP_DEFAULT_EMAIL_DELETE_SIGNATURE_ERROR',

  getEmailSignature: () => ({
    type: actions.APP_DEFAULT__EMAIL_SIGNATURE,
  }),

  uploadEmailSignature: (type) => ({
    type: actions.UPLOAD_APP_DEFAULT__EMAIL_SIGNATURE,
    payload: type,
  }),

  deleteEmailSignature: (type) => ({
    type: actions.APP_DEFAULT_EMAIL_DELETE_SIGNATURE,
    payload: type,
  }),
};

export default actions;
