const actions = {
  CALCULATOR_AFFORDABILITY_ADMIN: 'CALCULATOR_AFFORDABILITY_ADMIN',
  CALCULATOR_AFFORDABILITY_ADMIN_SUCCESS:
    'CALCULATOR_AFFORDABILITY_ADMIN_SUCCESS',
  CALCULATOR_AFFORDABILITY_ADMIN_ERROR: 'CALCULATOR_AFFORDABILITY_ADMIN_ERROR',

  SAVE_CALCULATOR_AFFORDABILITY_ADMIN: 'SAVE_CALCULATOR_AFFORDABILITY_ADMIN',
  SAVE_CALCULATOR_AFFORDABILITY_ADMIN_SUCCESS:
    'SAVE_CALCULATOR_AFFORDABILITY_ADMIN_SUCCESS',
  SAVE_CALCULATOR_AFFORDABILITY_ADMIN_ERROR:
    'SAVE_CALCULATOR_AFFORDABILITY_ADMIN_ERROR',

  DELETE_CALCULATOR_AFFORDABILITY_ADMIN_LOAN_FECTOR:
    'DELETE_CALCULATOR_AFFORDABILITY_ADMIN_LOAN_FACTOR',
  DELETE_CALCULATOR_AFFORDABILITY_ADMIN_LOAN_FECTOR_SUCCESS:
    'DELETE_CALCULATOR_AFFORDABILITY_ADMIN_LOAN_FECTOR_SUCCESS',
  DELETE_CALCULATOR_AFFORDABILITY_ADMIN_LOAN_FECTOR_ERROR:
    'DELETE_CALCULATOR_AFFORDABILITY_ADMIN_LOAN_FECTOR_ERROR',

  getAffordability: () => {
    return {
      type: actions.CALCULATOR_AFFORDABILITY_ADMIN,
    };
  },

  saveAffordability: (payload) => ({
    type: actions.SAVE_CALCULATOR_AFFORDABILITY_ADMIN,
    payload,
  }),
  deleteAffordabilityLoanFector: (payload) => ({
    type: actions.DELETE_CALCULATOR_AFFORDABILITY_ADMIN_LOAN_FECTOR,
    payload,
  }),
};

export default actions;
