const actions = {
  MARKETING_EMAIL_SIGNATURE: 'MARKETING_EMAIL_SIGNATURE',
  MARKETING_EMAIL_SIGNATURE_SUCCESS: 'MARKETING_EMAIL_SIGNATURE_SUCCESS',
  MARKETING_EMAIL_SIGNATURE_ERROR: 'MARKETING_EMAIL_SIGNATURE_ERROR',

  UPLOAD_MARKETING_EMAIL_SIGNATURE: 'UPLOAD_MARKETING_EMAIL_SIGNATURE',
  UPLOAD_MARKETING_EMAIL_SIGNATURE_SUCCESS:
    'UPLOAD_MARKETING_EMAIL_SIGNATURE_SUCCESS',
  UPLOAD_MARKETING_EMAIL_SIGNATURE_ERROR:
    'UPLOAD_MARKETING_EMAIL_SIGNATURE_ERROR',

  MARKETING_EMAIL_DELETE_SIGNATURE: 'MARKETING_EMAIL_DELETE_SIGNATURE',
  MARKETING_EMAIL_DELETE_SIGNATURE_SUCCESS:
    'MARKETING_EMAIL_DELETE_SIGNATURE_SUCCESS',
  MARKETING_EMAIL_DELETE_SIGNATURE_ERROR:
    'MARKETING_EMAIL_DELETE_SIGNATURE_ERROR',

  DEFAULT_MARKETING_EMAIL_SIGNATURE: 'DEFAULT_MARKETING_EMAIL_SIGNATURE',
  DEFAULT_MARKETING_EMAIL_SIGNATURE_SUCCESS:
    'DEFAULT_MARKETING_EMAIL_SIGNATURE_SUCCESS',
  DEFAULT_MARKETING_EMAIL_SIGNATURE_ERROR:
    'DEFAULT_MARKETING_EMAIL_SIGNATURE_ERROR',

  getEmailSignature: () => ({
    type: actions.MARKETING_EMAIL_SIGNATURE,
  }),

  defaultEmailSignature: () => ({
    type: actions.DEFAULT_MARKETING_EMAIL_SIGNATURE,
  }),
  uploadEmailSignature: (type) => ({
    type: actions.UPLOAD_MARKETING_EMAIL_SIGNATURE,
    payload: type,
  }),

  deleteEmailSignature: (type) => ({
    type: actions.MARKETING_EMAIL_DELETE_SIGNATURE,
    payload: type,
  }),
};

export default actions;
