const actions = {
  CONTENT_LO_LOAN_PROGRAM: 'CONTENT_LOAN_PROGRAM',
  CONTENT_LO_LOAN_PROGRAM_SUCCESS: 'CONTENT_LOAN_PROGRAM_SUCCESS',
  CONTENT_LO_LOAN_PROGRAM_ERROR: 'CONTENT_LOAN_PROGRAM_ERROR',

  SAVE_CONTENT_LO_LOAN_PROGRAM: 'SAVE_CONTENT_LO_LOAN_PROGRAM',
  SAVE_CONTENT_LO_LOAN_PROGRAM_SUCCESS: 'SAVE_CONTENT_LO_LOAN_PROGRAM_SUCCESS',
  SAVE_CONTENT_LO_LOAN_PROGRAM_ERROR: 'SAVE_CONTENT_LO_LOAN_PROGRAM_ERROR',

  DEFAULT_CONTENT_LO_LOAN_PROGRAM: 'DEFAULT_CONTENT_LO_LOAN_PROGRAM',
  DEFAULT_CONTENT_LO_LOAN_PROGRAM_SUCCESS:
    'DEFAULT_CONTENT_LO_LOAN_PROGRAM_SUCCESS',
  DEFAULT_CONTENT_LO_LOAN_PROGRAM_ERROR:
    'DEFAULT_CONTENT_LO_LOAN_PROGRAM_ERROR',

  EDIT_CONTENT_LO_LOAN_PROGRAM: 'EDIT_CONTENT_LO_LOAN_PROGRAM',
  EDIT_CONTENT_LO_LOAN_PROGRAM_SUCCESS: 'EDIT_CONTENT_LO_LOAN_PROGRAM_SUCCESS',
  EDIT_CONTENT_LO_LOAN_PROGRAM_ERROR: 'EDIT_CONTENT_LO_LOAN_PROGRAM_ERROR',

  DELETE_CONTENT_LO_LOAN_PROGRAM: 'DELETE_CONTENT_LOAN_PROGRAM',
  DELETE_CONTENT_LO_LOAN_PROGRAM_SUCCESS: 'DELETE_CONTENT_LOAN_PROGRAM_SUCCESS',
  DELETE_CONTENT_LO_LOAN_PROGRAM_ERROR: 'DELETE_CONTENT_LOAN_PROGRAM_ERROR',

  REARRANGE_LOAN_PROGRAM: 'REARRANGE_LOAN_PROGRAM',

  loanProgramList: (payload) => {
    return {
      type: actions.CONTENT_LO_LOAN_PROGRAM,
      payload,
    };
  },
  rearrangeLoanProgram: (payload) => ({
    type: actions.REARRANGE_LOAN_PROGRAM,
    payload,
  }),
  defaultLoanProgramList: () => ({
    type: actions.DEFAULT_CONTENT_LO_LOAN_PROGRAM,
  }),
  setIsDefaultDataEmpty: (payload) => ({
    type: actions.DEFAULT_CONTENT_LO_LOAN_PROGRAM_ERROR,
    payload,
  }),
  editLoanProgram: (payload) => ({
    type: actions.EDIT_CONTENT_LO_LOAN_PROGRAM,
    payload,
  }),
  deleteLoanProgram: (payload) => ({
    type: actions.DELETE_CONTENT_LO_LOAN_PROGRAM,
    payload,
  }),

  saveLoanProgram: (type) => ({
    type: actions.SAVE_CONTENT_LO_LOAN_PROGRAM,
    payload: type,
  }),
};

export default actions;
