const actions = {
  APP_DEF_DASHBOARD_MENU_ADMIN: 'APP_DEF_DASHBOARD_MENU_ADMIN',
  APP_DEF_DASHBOARD_MENU_ADMIN_SUCCESS: 'APP_DEF_DASHBOARD_MENU_ADMIN_SUCCESS',
  APP_DEF_DASHBOARD_MENU_ADMIN_ERROR: 'APP_DEF_DASHBOARD_MENU_ADMIN_ERROR',

  APP_DEF_MENU_ADMIN: 'APP_DEF_MENU_ADMIN',
  APP_DEF_MENU_ADMIN_SUCCESS: 'APP_DEF_MENU_ADMIN_SUCCESS',
  APP_DEF_MENU_ADMIN_ERROR: 'APP_DEF_MENU_ADMIN_ERROR',

  ADD_CUSTOM_LINK_DASHBOARD_ADMIN: 'ADD_CUSTOM_LINK_DASHBOARD_ADMIN',
  ADD_CUSTOM_LINK_DASHBOARD_ADMIN_SUCCESS:
    'ADD_CUSTOM_LINK_DASHBOARD_ADMIN_SUCCESS',
  ADD_CUSTOM_LINK_DASHBOARD_ADMIN_ERROR:
    'ADD_CUSTOM_LINK_DASHBOARD_ADMIN_ERROR',

  ADD_CUSTOM_LINK_APP_ADMIN: 'ADD_CUSTOM_LINK_APP_ADMIN',
  ADD_CUSTOM_LINK_APP_ADMIN_SUCCESS: 'ADD_CUSTOM_LINK_APP_ADMIN_SUCCESS',
  ADD_CUSTOM_LINK_APP_ADMIN_ERROR: 'ADD_CUSTOM_LINK_APP_ADMIN_ERROR',

  SAVE_APP_DEF_DASHBOARD_MENU_ADMIN: 'SAVE_APP_DEF_DASHBOARD_MENU_ADMIN',
  SAVE_APP_DEF_DASHBOARD_MENU_ADMIN_SUCCESS:
    'SAVE_APP_DEF_DASHBOARD_MENU_ADMIN_SUCCESS',
  SAVE_APP_DEF_DASHBOARD_MENU_ADMIN_ERROR:
    'SAVE_APP_DEF_DASHBOARD_MENU_ADMIN_ERROR',

  SAVE_APP_DEF_MENU_ADMIN: 'SAVE_APP_DEF_MENU_ADMIN',
  SAVE_APP_DEF_MENU_ADMIN_SUCCESS: 'SAVE_APP_DEF_MENU_ADMIN_SUCCESS',
  SAVE_APP_DEF_MENU_ADMIN_ERROR: 'SAVE_APP_DEF_MENU_ADMIN_ERROR',

  APP_DEF_MORTGAGE_GUIDE_ADMIN: 'APP_DEF_MORTGAGE_GUIDE_ADMIN',
  APP_DEF_MORTGAGE_GUIDE_ADMIN_SUCCESS: 'APP_DEF_MORTGAGE_GUIDE_ADMIN_SUCCESS',
  APP_DEF_MORTGAGE_GUIDE_ADMIN_ERROR: 'APP_DEF_MORTGAGE_GUIDE_ADMIN_ERROR',

  CHANGE_APP_DEF_MORTGAGE_GUIDE_ADMIN: 'CHANGE_APP_DEF_MORTGAGE_GUIDE_ADMIN',
  CHANGE_APP_DEF_MORTGAGE_GUIDE_ADMIN_SUCCESS:
    'CHANGE_APP_DEF_MORTGAGE_GUIDE_ADMIN_SUCCESS',
  CHANGE_APP_DEF_MORTGAGE_GUIDE_ADMIN_ERROR:
    'CHANGE_APP_DEF_MORTGAGE_GUIDE_ADMIN_ERROR',

  DELETE_APP_DEF_MENU_ADMIN: 'DELETE_APP_DEF_MENU_ADMIN',
  DELETE_APP_DEF_APP_MENU_ADMIN_SUCCESS:
    'DELETE_APP_DEF_APP_MENU_ADMIN_SUCCESS',
  DELETE_APP_DEF_DASHBOARD_MENU_ADMIN_SUCCESS:
    'DELETE_APP_DEF_DASHBOARD_MENU_ADMIN_SUCCESS',

  appDashboardMenuList: () => ({
    type: actions.APP_DEF_DASHBOARD_MENU_ADMIN,
  }),
  appMortgageGuide: () => ({
    type: actions.APP_DEF_MORTGAGE_GUIDE_ADMIN,
  }),

  deleteAdminMenu: (payload) => ({
    type: actions.DELETE_APP_DEF_MENU_ADMIN,
    payload,
  }),
  appMenuList: () => ({
    type: actions.APP_DEF_MENU_ADMIN,
  }),
  addCustomLinkDashboard: (payload) => ({
    type: actions.ADD_CUSTOM_LINK_DASHBOARD_ADMIN,
    payload,
  }),
  addCustomLinkApp: (payload) => ({
    type: actions.ADD_CUSTOM_LINK_APP_ADMIN,
    payload,
  }),
  appDashboardMenuSave: (payload) => ({
    type: actions.SAVE_APP_DEF_DASHBOARD_MENU_ADMIN,
    payload,
  }),
  appMortgageGuideChange: (payload) => ({
    type: actions.CHANGE_APP_DEF_MORTGAGE_GUIDE_ADMIN,
    payload,
  }),
  appMenuSave: (payload) => ({
    type: actions.SAVE_APP_DEF_MENU_ADMIN,
    payload,
  }),
};
export default actions;
