const actions = {
  CALCULATOR_FHA_ADMIN: 'CALCULATOR_FHA_ADMIN',
  CALCULATOR_FHA_ADMIN_SUCCESS: 'CALCULATOR_FHA_ADMIN_SUCCESS',
  CALCULATOR_FHA_ADMIN_ERROR: 'CALCULATOR_FHA_ADMIN_ERROR',

  SAVE_CALCULATOR_FHA_ADMIN: 'EDIT_CALCULATOR_FHA_ADMIN',
  SAVE_CALCULATOR_FHA_ADMIN_SUCCESS: 'EDIT_CALCULATOR_FHA_ADMIN_SUCCESS',
  SAVE_CALCULATOR_FHA_ADMIN_ERROR: 'EDIT_CALCULATOR_FHA_ADMIN_ERROR',

  DELETE_CALCULATOR_FHA_ADMIN_LOAN_FECTOR:
    'DELETE_CALCULATOR_FHA_ADMIN_LOAN_FACTOR',
  DELETE_CALCULATOR_FHA_ADMIN_LOAN_FECTOR_SUCCESS:
    'DELETE_CALCULATOR_FHA_ADMIN_LOAN_FECTOR_SUCCESS',
  DELETE_CALCULATOR_FHA_ADMIN_LOAN_FECTOR_ERROR:
    'DELETE_CALCULATOR_FHA_ADMIN_LOAN_FECTOR_ERROR',

  getFHA: () => {
    return {
      type: actions.CALCULATOR_FHA_ADMIN,
    };
  },

  saveFHA: (payload) => ({
    type: actions.SAVE_CALCULATOR_FHA_ADMIN,
    payload,
  }),
  deleteFHALoanFector: (payload) => ({
    type: actions.DELETE_CALCULATOR_FHA_ADMIN_LOAN_FECTOR,
    payload,
  }),
};

export default actions;
