const actions = {
  LO_SUBSCRIPTION: 'LO_SUBSCRIPTION',
  LO_SUBSCRIPTION_SUCCESS: 'LO_SUBSCRIPTION_SUCCESS',
  LO_SUBSCRIPTION_ERROR: 'LO_SUBSCRIPTION_ERROR',

  CANCEL_LO_SUBSCRIPTION: 'CANCEL_LO_SUBSCRIPTION',
  CANCEL_LO_SUBSCRIPTION_SUCCESS: 'CANCEL_LO_SUBSCRIPTION_SUCCESS',
  CANCEL_LO_SUBSCRIPTION_ERROR: 'CANCEL_LO_SUBSCRIPTION_ERROR',

  LO_SUBSCRIBE: 'LO_SUBSCRIBE',
  LO_SUBSCRIBE_SUCCESS: 'LO_SUBSCRIBE_SUCCESS',
  LO_SUBSCRIBE_ERROR: 'LO_SUBSCRIBE_ERROR',

  LO_ALL_PLAN_SUBSCRIPTION: 'LO_ALL_PLAN_SUBSCRIPTION',
  LO_ALL_PLAN_SUBSCRIPTION_SUCCESS: 'LO_ALL_PLAN_SUBSCRIPTION_SUCCESS',
  LO_ALL_PLAN_SUBSCRIPTION_ERROR: 'LO_ALL_PLAN_SUBSCRIPTION_ERROR',

  LO_SUPPORT_FAQS: 'LO_SUPPORT_FAQS',
  LO_SUPPORT_FAQS_SUCCESS: 'LO_SUPPORT_FAQS_SUCCESS',
  LO_SUPPORT_FAQS_ERROR: 'LO_SUPPORT_FAQS_ERROR',

  LO_SUPPORT_GUIDE: 'LO_SUPPORT_GUIDE',
  LO_SUPPORT_GUIDE_SUCCESS: 'LO_SUPPORT_GUIDE_SUCCESS',
  LO_SUPPORT_GUIDE_ERROR: 'LO_SUPPORT_GUIDE_ERROR',

  LO_SUBSCRIPTION_APPLY_PROMO_CODE: 'LO_SUBSCRIPTION_APPLY_PROMO_CODE',
  LO_SUBSCRIPTION_APPLY_PROMO_CODE_SUCCESS:
    'LO_SUBSCRIPTION_APPLY_PROMO_CODE_SUCCESS',
  LO_SUBSCRIPTION_APPLY_PROMO_CODE_ERROR:
    'LO_SUBSCRIPTION_APPLY_PROMO_CODE_ERROR',

  GET_SUBSCRIPTION_APPLY_PROMO_CODE: 'GET_SUBSCRIPTION_APPLY_PROMO_CODE',
  GET_SUBSCRIPTION_APPLY_PROMO_CODE_SUCCESS:
    'GET_SUBSCRIPTION_APPLY_PROMO_CODE_SUCCESS',

  getSubscription: () => ({
    type: actions.LO_SUBSCRIPTION,
  }),
  cancelSubscription: () => ({
    type: actions.CANCEL_LO_SUBSCRIPTION,
  }),
  subscribePlan: (payload) => ({
    type: actions.LO_SUBSCRIBE,
    payload,
  }),
  getAllSubscriptionPlan: () => ({
    type: actions.LO_ALL_PLAN_SUBSCRIPTION,
  }),
  getLOSupportFaqs: () => ({
    type: actions.LO_SUPPORT_FAQS,
  }),
  getLOSupportGUide: () => ({
    type: actions.LO_SUPPORT_GUIDE,
  }),
  subscriptionApplyPromoCode: (payload) => ({
    type: actions.LO_SUBSCRIPTION_APPLY_PROMO_CODE,
    payload,
  }),
  GetApplyPromoCode: () => ({
    type: actions.GET_SUBSCRIPTION_APPLY_PROMO_CODE,
  }),
};

export default actions;
