const actions = {
  CALCULATOR_TYPES_ADMIN: 'CALCULATOR_TYPES_ADMIN',
  CALCULATOR_TYPES_ADMIN_SUCCESS: 'CALCULATOR_TYPES_ADMIN_SUCCESS',
  CALCULATOR_TYPES_ADMIN_ERROR: 'CALCULATOR_TYPES_ADMIN_ERROR',

  CALCULATOR_TYPES_ADMIN: 'CALCULATOR_TYPES_ADMIN',
  CALCULATOR_TYPES_ADMIN_SUCCESS: 'CALCULATOR_TYPES_ADMIN_SUCCESS',
  CALCULATOR_TYPES_ADMIN_ERROR: 'CALCULATOR_TYPES_ADMIN_ERROR',

  EDIT_CALCULATOR_TYPES_ADMIN: 'EDIT_CALCULATOR_TYPES_ADMIN',
  EDIT_CALCULATOR_TYPES_ADMIN_SUCCESS: 'EDIT_CALCULATOR_TYPES_ADMIN_SUCCESS',
  EDIT_CALCULATOR_TYPES_ADMIN_ERROR: 'EDIT_CALCULATOR_TYPES_ADMIN_ERROR',

  getTypes: () => {
    return {
      type: actions.CALCULATOR_TYPES_ADMIN,
    };
  },

  editTypes: (payload) => ({
    type: actions.EDIT_CALCULATOR_TYPES_ADMIN,
    payload,
  }),

  saveDisclaimer: (payload) => ({
    type: actions.CALCULATOR_TYPES_ADMIN,
    payload,
  }),
};

export default actions;
